<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="6" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-08-25T21:23:28 IST" name="Suite" finished-at="2024-08-25T21:23:51 IST" duration-ms="22582">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidation.LoginErrorValidation()[pri:0, instance:ChaitraAcademy.tests.ErrorValidation@6950ed69]" name="LoginErrorValidation" class="ChaitraAcademy.tests.ErrorValidation"/>
      </group> <!-- ErrorHandling -->
    </groups>
    <test started-at="2024-08-25T21:23:28 IST" name="Error Validation test" finished-at="2024-08-25T21:23:42 IST" duration-ms="14397">
      <class name="ChaitraAcademy.tests.ErrorValidation">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:ChaitraAcademy.tests.ErrorValidation@6950ed69]" started-at="2024-08-25T21:23:28 IST" name="launchApplication" finished-at="2024-08-25T21:23:31 IST" duration-ms="3117" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="LoginErrorValidation()[pri:0, instance:ChaitraAcademy.tests.ErrorValidation@6950ed69]" started-at="2024-08-25T21:23:31 IST" name="LoginErrorValidation" finished-at="2024-08-25T21:23:32 IST" duration-ms="618" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect mail or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect mail or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at ChaitraAcademy.tests.ErrorValidation.LoginErrorValidation(ErrorValidation.java:36)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:ChaitraAcademy.tests.ErrorValidation@6950ed69]" started-at="2024-08-25T21:23:32 IST" name="tearDown" finished-at="2024-08-25T21:23:32 IST" duration-ms="116" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:ChaitraAcademy.tests.ErrorValidation@6950ed69]" started-at="2024-08-25T21:23:32 IST" name="launchApplication" finished-at="2024-08-25T21:23:34 IST" duration-ms="2388" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="LoginErrorValidation()[pri:0, instance:ChaitraAcademy.tests.ErrorValidation@6950ed69]" started-at="2024-08-25T21:23:34 IST" name="LoginErrorValidation" finished-at="2024-08-25T21:23:35 IST" duration-ms="889" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect mail or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect mail or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at ChaitraAcademy.tests.ErrorValidation.LoginErrorValidation(ErrorValidation.java:36)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:ChaitraAcademy.tests.ErrorValidation@6950ed69]" started-at="2024-08-25T21:23:35 IST" name="tearDown" finished-at="2024-08-25T21:23:36 IST" duration-ms="129" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:ChaitraAcademy.tests.ErrorValidation@6950ed69]" started-at="2024-08-25T21:23:36 IST" name="launchApplication" finished-at="2024-08-25T21:23:37 IST" duration-ms="1312" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="ProductErrorValidation()[pri:0, instance:ChaitraAcademy.tests.ErrorValidation@6950ed69]" started-at="2024-08-25T21:23:37 IST" name="ProductErrorValidation" finished-at="2024-08-25T21:23:42 IST" duration-ms="5338" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:ChaitraAcademy.tests.ErrorValidation@6950ed69]" started-at="2024-08-25T21:23:42 IST" name="tearDown" finished-at="2024-08-25T21:23:42 IST" duration-ms="80" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- ChaitraAcademy.tests.ErrorValidation -->
    </test> <!-- Error Validation test -->
    <test started-at="2024-08-25T21:23:28 IST" name="Submit order test" finished-at="2024-08-25T21:23:51 IST" duration-ms="22582">
      <class name="ChaitraAcademy.tests.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:ChaitraAcademy.tests.SubmitOrderTest@24959ca4]" started-at="2024-08-25T21:23:28 IST" name="launchApplication" finished-at="2024-08-25T21:23:30 IST" duration-ms="1961" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="SubmitOrder()[pri:0, instance:ChaitraAcademy.tests.SubmitOrderTest@24959ca4]" started-at="2024-08-25T21:23:30 IST" name="SubmitOrder" finished-at="2024-08-25T21:23:48 IST" duration-ms="18524" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:ChaitraAcademy.tests.SubmitOrderTest@24959ca4]" started-at="2024-08-25T21:23:48 IST" name="tearDown" finished-at="2024-08-25T21:23:49 IST" duration-ms="74" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:ChaitraAcademy.tests.SubmitOrderTest@24959ca4]" started-at="2024-08-25T21:23:49 IST" name="launchApplication" finished-at="2024-08-25T21:23:50 IST" duration-ms="1349" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="OrderHistoryTest()[pri:0, instance:ChaitraAcademy.tests.SubmitOrderTest@24959ca4]" started-at="2024-08-25T21:23:50 IST" name="OrderHistoryTest" finished-at="2024-08-25T21:23:50 IST" depends-on-methods="ChaitraAcademy.tests.SubmitOrderTest.SubmitOrder" duration-ms="560" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistoryTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:ChaitraAcademy.tests.SubmitOrderTest@24959ca4]" started-at="2024-08-25T21:23:50 IST" name="tearDown" finished-at="2024-08-25T21:23:51 IST" duration-ms="83" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- ChaitraAcademy.tests.SubmitOrderTest -->
    </test> <!-- Submit order test -->
  </suite> <!-- Suite -->
</testng-results>
